2024-08-10 00:06:19,430 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in C:\PYTHON\projects\GitHub\klepak\klepak.py:33]
2024-08-10 00:06:19,431 WARNING: Nieznany adres IP: 127.0.0.1. Blokowanie po³¹czenia. [in C:\PYTHON\projects\GitHub\klepak\klepak.py:54]
2024-08-10 00:06:19,431 ERROR: Exception on / [GET] [in c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\PYTHON\projects\GitHub\klepak\klepak.py", line 48, in block_non_polish_ips
    response = geoip_reader.country(request.remote_addr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\geoip2\database.py", line 139, in country
    Country, self._model_for(geoip2.models.Country, "Country", ip_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\geoip2\database.py", line 253, in _model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\geoip2\database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\flask\app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PYTHON\projects\GitHub\klepak\.venv\Lib\site-packages\flask\app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PYTHON\projects\GitHub\klepak\klepak.py", line 55, in block_non_polish_ips
    ip_blocks_unknown = ip_blocks_unknown + 1
                        ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'ip_blocks_unknown' where it is not associated with a value
2024-08-10 00:12:31,959 INFO: Klepak startup [in c:\PYTHON\projects\GitHub\klepak\klepak.py:28]
2024-08-10 00:12:31,959 INFO: Baza GeoIP za³adowana [in c:\PYTHON\projects\GitHub\klepak\klepak.py:42]
2024-08-10 00:12:32,499 INFO: Klepak startup [in c:\PYTHON\projects\GitHub\klepak\klepak.py:28]
2024-08-10 00:12:32,499 INFO: Baza GeoIP za³adowana [in c:\PYTHON\projects\GitHub\klepak\klepak.py:42]
2024-08-10 00:12:49,385 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in c:\PYTHON\projects\GitHub\klepak\klepak.py:33]
2024-08-10 00:12:49,385 WARNING: Nieznany adres IP: 127.0.0.1. Blokowanie po³¹czenia. [in c:\PYTHON\projects\GitHub\klepak\klepak.py:53]
2024-08-10 00:12:51,664 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in c:\PYTHON\projects\GitHub\klepak\klepak.py:33]
2024-08-10 00:12:51,665 WARNING: Nieznany adres IP: 127.0.0.1. Blokowanie po³¹czenia. [in c:\PYTHON\projects\GitHub\klepak\klepak.py:53]
2024-08-10 00:15:15,451 INFO: Klepak startup [in c:\PYTHON\projects\GitHub\klepak\klepak.py:28]
2024-08-10 00:15:15,451 INFO: Baza GeoIP za³adowana [in c:\PYTHON\projects\GitHub\klepak\klepak.py:42]
2024-08-10 00:15:20,627 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in c:\PYTHON\projects\GitHub\klepak\klepak.py:33]
2024-08-10 00:15:20,627 WARNING: Nieznany adres IP: 127.0.0.1. Blokowanie po³¹czenia. [in c:\PYTHON\projects\GitHub\klepak\klepak.py:53]
2024-08-10 00:15:24,054 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in c:\PYTHON\projects\GitHub\klepak\klepak.py:33]
2024-08-10 00:15:24,055 WARNING: Nieznany adres IP: 127.0.0.1. Blokowanie po³¹czenia. [in c:\PYTHON\projects\GitHub\klepak\klepak.py:53]
2024-08-10 00:18:51,673 INFO: Klepak startup [in c:\PYTHON\projects\GitHub\klepak\klepak.py:28]
2024-08-10 00:18:51,673 INFO: Baza GeoIP za³adowana [in c:\PYTHON\projects\GitHub\klepak\klepak.py:42]
2024-08-10 00:28:14,608 INFO: Klepak startup [in c:\PYTHON\projects\GitHub\klepak\klepak.py:29]
2024-08-10 00:28:14,608 INFO: Baza GeoIP za³adowana [in c:\PYTHON\projects\GitHub\klepak\klepak.py:43]
2024-08-10 00:28:20,905 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in c:\PYTHON\projects\GitHub\klepak\klepak.py:34]
2024-08-10 00:28:20,905 INFO: Adres IP: 127.0.0.1 znajduje siê na liœcie wyj¹tków, dostêp przyznany. [in c:\PYTHON\projects\GitHub\klepak\klepak.py:48]
2024-08-10 00:28:26,463 INFO: Mamy goœcia - Adres IP: 127.0.0.1, URL: http://127.0.0.1:20162/help, Metoda: GET, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 [in c:\PYTHON\projects\GitHub\klepak\klepak.py:34]
2024-08-10 00:28:26,464 INFO: Adres IP: 127.0.0.1 znajduje siê na liœcie wyj¹tków, dostêp przyznany. [in c:\PYTHON\projects\GitHub\klepak\klepak.py:48]
